### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by Wuchuq** [yfsong0709/ResGCNv1#6]
![image](https://user-images.githubusercontent.com/74027834/111864722-a5d4f580-899d-11eb-9f61-3385e337e830.png)
![image](https://user-images.githubusercontent.com/74027834/111864735-aff6f400-899d-11eb-8a79-ca8a8542b361.png)

**Comment by yfsong0709** [comment]
Sorry, I have not seen this issue before. It looks like a GPU parallel problem in PyTorch, please try to use one GPU to train our model. GPU settings can be found in the corresponding yaml files (Parameter 'gpus'). If one GPU is OK, this issue may be caused by the PyTorch with low version. Otherwise, you can put the new error message here.
